How to run the API from terminal with maven
ayudadigital/huelladigital pull request #12
Opened 2020-05-23 19:05 UTC by RubenZagon

2020-05-24 12:05 UTC, ibaiul requested changes
1- In the section where it explains how to run the tests, maybe it is worth mentioning that the docker daemon must already be running in your system in order to run the integrations tests that require it.

2- Notice that the platform can also be run directly from the IDE by just right clicking in the Application.java file which might be more convenient in some cases.

3- I would mention as well that before running the the backend locally the docker-compose file under backend/docker/local directory must be up to provide the database/localstack dependencies

2020-05-30 22:08 UTC, RubenZagon commented
> I would mention as well that before running the the backend locally the docker-compose file under backend/docker/local directory must be up to provide the database/localstack dependencies

Very nice observation @ibaiul thanks for the feedback, **i did the changes you comment** 🚀

2020-06-04 13:17 UTC, carlosble approved these changes

2020-06-04 17:17 UTC, ibaiul approved these changes

2020-06-04 21:18 UTC, merged