Add swagger documentation
ayudadigital/huelladigital pull request #48
Opened 2020-10-06 11:29 UTC by mariasoria

* Added swagger comments to controllers. 
* Fixed possible issues in SonarCloud with RemoteStorageService.java

2020-10-10 14:47 UTC, ibaiul requested changes

2020-10-10 14:47 UTC, ibaiul commented on backend/src/main/java/com/huellapositiva/domain/service/RemoteStorageService.java
> +        }
Check for value equals null rather than catching a NPE

2020-10-10 14:47 UTC, ibaiul commented on backend/src/main/java/com/huellapositiva/domain/service/RemoteStorageService.java
> +        }
Check for value equals null rather than catching a NPE

2020-10-10 14:47 UTC, ibaiul commented on backend/src/main/java/com/huellapositiva/domain/service/RemoteStorageService.java
>          if(!extension.equalsIgnoreCase(".pdf")) {
When comparing Strings always put the static value first to avoid NPE ".pdf".equalsIgnoreCase(extension)

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/application/controller/ProposalApiController.java
> +                            responseCode = "201",
Si no me equivoco el metodo responde un HTTPStatus.OK es un codigo 200 pero en la documentación tenemos el 201

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/application/controller/ProposalApiController.java
> +                            responseCode = "201",
Si no me equivoco el metodo responde un HTTPStatus.OK es un codigo 200 pero en la documentación tenemos el 201

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/application/controller/ProposalApiController.java
> +                            responseCode = "201",
Si no me equivoco el metodo responde un HTTPStatus.OK es un codigo 200 pero en la documentación tenemos el 201

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/application/controller/ProposalApiController.java
> +                            responseCode = "201",
Si no me equivoco el metodo responde un HTTPStatus.OK es un codigo 200 pero en la documentación tenemos el 201

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/application/controller/VolunteerApiController.java
> +                            responseCode = "201",
Si no me equivoco el metodo responde un HTTPStatus.OK es un codigo 200 pero en la documentación tenemos el 201

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/domain/service/RemoteStorageService.java
> +            destinationFileName += getExtension(image.getOriginalFilename());
Un NullPointerException nunca se debe capturar. Se debe actuar con anterioridad para capturarlo. En este caso, seguramente la parte `image.getIriginalFilename()` lance un NPE por que image es null. se deberia hacer un check de image no es null antes de concatenarla.
Tambien considerar el uso de StringBuffer en lugar de String

2020-10-13 15:41 UTC, manumoranchel commented on backend/src/main/java/com/huellapositiva/domain/service/RemoteStorageService.java
> +            extension = getExtension(cv.getOriginalFilename());
Un NullPointerException nunca se debe capturar. Se debe actuar con anterioridad para capturarlo. En este caso, seguramente la parte `image.getIriginalFilename()` lance un NPE por que image es null. se deberia hacer un check de image no es null antes de concatenarla.
Tambien considerar el uso de StringBuffer en lugar de String

2020-10-13 18:10 UTC, mariasoria commented
@manumoranchel Con los últimos cambios que hemos hecho contigo gestionando lo del NullPointerException ya ha pasado el SonarCloud. 🥇

2020-10-14 07:18 UTC, manumoranchel approved these changes

2020-10-14 07:19 UTC, manumoranchel commented
Fantastico chicos. Ahora teneis mi approval pero sigo viendo una petición de cambios de Ibai. Esperemos a que él lo revise y apruebe antes de mergear. Buen trabajo

2020-10-15 17:47 UTC, ibaiul approved these changes

2020-10-16 09:11 UTC, merged